bqwebsite/blueprints/main.py
import os

from flask import render_template, request, redirect, url_for, Blueprint, current_app, flash, send_from_directory, \
    jsonify
from sqlalchemy.orm import joinedload, contains_eager

from ..models import Category, Product, News, Brand, Honor, Banner, Introduce, Photo, NewsCategory, \
    IntroduceCategory, Contact, ContactCategory, Subject, Research, ResearchCategory, IndexAbout

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
# 主页
def index():
    banner = Banner.query.all()
    index_about = IndexAbout.query.first()
    categories = Category.query.filter(Category.status == True).order_by(Category.id).all()
    filtered_categories = [category for category in categories if category.id >= 2][:8]
    news = News.query.filter(News.status == True).order_by(News.timestamp.desc()).all()
    return render_template('main/index.html', banner=banner, index_about=index_about, categories=filtered_categories, news=news)


@main_bp.route('/news-category/<int:news_category_id>')
# 新闻分类页面
def show_news_category(news_category_id):
    news_category = NewsCategory.query.get_or_404(news_category_id)
    if not news_category.status:
        flash('该新闻分类不存在', 'info')
        return redirect(url_for('main.news'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_NEWS_PER_PAGE']
    pagination = News.query.with_parent(news_category).filter(News.status == True).order_by(
        News.timestamp.desc()).paginate(page=page,
                                        per_page=per_page)
    news_list = pagination.items

    return render_template('main/news_category.html', news_category=news_category, news_list=news_list,
                           pagination=pagination)


@main_bp.route('/news/<int:news_id>')
# 新闻详细页面
def show_news(news_id):
    news_detail = News.query.get_or_404(news_id)
    if not news_detail.status:
        flash('该新闻不存在', 'info')
        return redirect(url_for('main.news'))
    return render_template('main/news_detail.html', news_detail=news_detail)


@main_bp.route('/news/n/<int:news_id>')
# 下一篇文章
def news_next(news_id):
    news_n_detail = News.query.get_or_404(news_id)
    if not news_n_detail.status:
        flash('该文章不存在', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    news_n = News.query.with_parent(news_n_detail.newscategory).filter(
        News.timestamp < news_n_detail.timestamp, News.status == True).order_by(News.timestamp.desc()).first()

    if news_n is None:
        flash('已经是最后一篇文章', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    return redirect(url_for('main.show_news', news_id=news_n.id))


@main_bp.route('/news/p/<int:news_id>')
# 上一篇文章
def news_previous(news_id):
    news_p_detail = News.query.get_or_404(news_id)
    if not news_p_detail.status:
        flash('该文章不存在', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    news_p = News.query.with_parent(news_p_detail.newscategory).filter(
        News.timestamp > news_p_detail.timestamp, News.status == True).order_by(News.timestamp.asc()).first()

    if news_p is None:
        flash('已经是最新一篇文章', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    return redirect(url_for('main.show_news', news_id=news_p.id))


@main_bp.route('/news')
# 全部新闻页面
def news():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_NEWS_PER_PAGE']
    pagination = News.query.filter(News.status == True).order_by(News.timestamp.desc()).paginate(page=page,
                                                                                                 per_page=per_page)
    all_news = pagination.items
    return render_template('main/news.html', all_news=all_news, pagination=pagination)


@main_bp.route('/products')  # 所有产品
def product():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.filter(Product.status == True).order_by(Product.timestamp.desc()).paginate(page=page,
                                                                                                          per_page=per_page)
    products = pagination.items
    return render_template('main/products.html', products=products, pagination=pagination)


@main_bp.route('/category/<category>')  # 按剂型分类
def product_category(category):
    category = Category.query.filter_by(name=category).first_or_404()
    if not category.status:
        flash('该分类不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(category).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_category.html', category=category, pagination=pagination, products=products)


@main_bp.route('/brand/<brand>')  # 按商标分类
def product_brand(brand):
    brand = Brand.query.filter_by(name=brand).first_or_404()
    if not brand.status:
        flash('该商标不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(brand).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_brand.html', brand=brand, pagination=pagination, products=products)


@main_bp.route('/subject/<subject>')  # 按功能主治分类
def product_subject(subject):
    subject = Subject.query.filter_by(name=subject).first_or_404()
    if not subject.status:
        flash('该功能主治不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(subject).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_subject.html', subject=subject, pagination=pagination, products=products)


@main_bp.route('/products/n/<int:product_id>')
# 下一个品种
def product_next(product_id):
    product_n_detail = Product.query.get_or_404(product_id)
    if not product_n_detail.status:
        flash('该品种不存在', 'info')
        return redirect(url_for('main.product'))
    product_n = Product.query.with_parent(product_n_detail.category).filter(
        Product.timestamp > product_n_detail.timestamp).order_by(Product.timestamp.asc()).first()

    if product_n is None:
        flash('已经是一个', 'info')
        return redirect(url_for('main.show_product', product_id=product_id))
    return redirect(url_for('main.show_product', product_id=product_n.id))


@main_bp.route('/products/p/<int:product_id>')
# 上一个品种
def product_previous(product_id):
    product_p_detail = Product.query.get_or_404(product_id)
    if not product_p_detail.status:
        flash('该品种不存在', 'info')
        return redirect(url_for('main.product'))
    product_p = Product.query.with_parent(product_p_detail.category).filter(
        Product.timestamp < product_p_detail.timestamp).order_by(Product.timestamp.desc()).first()

    if product_p is None:
        flash('已经是最后一个', 'info')
        return redirect(url_for('main.show_product', product_id=product_id))
    return redirect(url_for('main.show_product', product_id=product_p.id))


@main_bp.route('/product_detail/<int:product_id>')  # 产品详细页面
def show_product(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.status:
        flash('该产品不存在', 'info')
        return redirect(url_for('main.product'))

    # 获取上一个品种
    product_p = Product.query.with_parent(product.category).filter(Product.timestamp < product.timestamp,
                                                                   Product.status == True).order_by(
        Product.timestamp.desc()).first()
    product_p_name = product_p.name if product_p else None
    # 获取下一个品种
    product_n = Product.query.with_parent(product.category).filter(Product.timestamp > product.timestamp,
                                                                   Product.status == True).order_by(
        Product.timestamp.asc()).first()
    product_n_name = product_n.name if product_n else None
    return render_template('main/product_detail.html', product=product, product_p_name=product_p_name,
                           product_n_name=product_n_name)


@main_bp.route('/introduce/<int:intro_id>')
# 公司介绍
def show_intro(intro_id):
    intro_categories = (
        IntroduceCategory.query
        .join(IntroduceCategory.introduces)  # 关联 Introduce 表
        .filter(Introduce.status == True)  # 筛选 status 为 True 的记录
        .options(contains_eager(IntroduceCategory.introduces))  # 预加载 introduces 数据
        .order_by(IntroduceCategory.id.asc())
        .all()
    )

    intro = Introduce.query.filter_by(id=intro_id, status=True).first_or_404()
    if not intro.status or not intro.introduce_category.status:
        flash('该介绍不存在', 'warning')
        return redirect(url_for('main.index'))
    return render_template('main/introduce_detail.html', intro=intro, intro_categories=intro_categories)


@main_bp.route('/honor')
# 荣誉介绍
def honor():
    return render_template('main/honor.html')


@main_bp.route('/contact/<int:contact_id>')
# 联系我们
def show_contact(contact_id):
    contact_categories = (
        ContactCategory.query
        .join(ContactCategory.contacts)
        .filter(Contact.status == True)
        .options(contains_eager(ContactCategory.contacts))
        .order_by(ContactCategory.id.asc())

bqwebsite/templates/main/_product_header.html
<header class="masthead bg-primary text-white text-center">
    <div class="product_bg_img"><img src="{{ url_for('static', filename='assets/img/banner-products.png') }}" class="img-fluid"
                                     alt=""></div>
</header>
<section class="product_header mt-2">
    <div class="container">
        <nav aria-label="breadcrumb" class="mb-2 mt-2 bg-light">
            <ol class="breadcrumb p-1">

                {% if request.view_args.get('brand') %}
                    <li class="breadcrumb-item"><a href="{{ url_for('main.product') }}"
                                                   class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">产品中心</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">按商标分类</li>
                    <li class="breadcrumb-item active" aria-current="page">{{ request.view_args.get('brand') }}</li>
                {% elif request.view_args.get('category') %}
                    <li class="breadcrumb-item"><a href="{{ url_for('main.product') }}"
                                                   class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">产品中心</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">按剂型分类</li>
                    <li class="breadcrumb-item active" aria-current="page">{{ request.view_args.get('category') }}</li>
                {% elif request.view_args.get('subject') %}
                    <li class="breadcrumb-item"><a href="{{ url_for('main.product') }}"
                                                   class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">产品中心</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">按功能分类</li>
                    <li class="breadcrumb-item active" aria-current="page">{{ request.view_args.get('subject') }}</li>
                {% else %}
                    <li class="breadcrumb-item"><a href="{{ url_for('main.product') }}"
                                                   class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">产品中心</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">全部产品</li>
                {% endif %}
            </ol>
        </nav>
        <div class="border-1" id="product-category">
            <div class="d-flex align-items-baseline border-bottom mb-2">
                <div class="nav-item">
                    <a href="#" class="nav-link disabled bg-light fw-bolder text-dark text-nowrap me-2 px-3 py-2"
                       tabindex="-1"
                       aria-disabled="true">按剂型：</a>
                </div>
                <ul class="nav d-flex flex-wrap align-items-baseline ps-0 mb-0">
                    {% for category in categories %}
                        {% if category.name != '未分类' %}
                            <li class="nav-item nav-pills">
                                <a href="{{ url_for('main.product_category', category=category.name) }}"
                                   class="nav-link {% if request.view_args.get('category') == category.name %}active{% endif %}">{{ category.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="d-flex align-items-baseline border-bottom mb-2">
                <div class="nav-item">
                    <a href="#" class="nav-link disabled bg-light fw-bolder text-dark text-nowrap me-2 px-3 py-2"
                       tabindex="-1"
                       aria-disabled="true">按商标：</a>
                </div>
                <ul class="nav d-flex flex-wrap align-items-baseline ps-0 mb-0">
                    {% for brand in brands %}
                        {% if brand.name != '未分类' %}
                            <li class="nav-item nav-pills">
                                <a href="{{ url_for('main.product_brand', brand=brand.name) }}"
                                   class="nav-link {% if request.view_args.get('brand') == brand.name %}active{% endif %}">{{ brand.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="d-flex align-items-baseline border-bottom mb-2">
                <div class="nav-item">
                    <a href="#" class="nav-link disabled bg-light fw-bolder text-dark text-nowrap me-2 px-3 py-2"
                       tabindex="-1"
                       aria-disabled="true">按功能：</a>
                </div>
                <ul class="nav d-flex flex-wrap align-items-baseline ps-0 mb-0">
                    {% for subject in subjects %}
                        {% if subject.name != '未分类' %}
                        <li class="nav-item nav-pills">
                            <a href="{{ url_for('main.product_subject', subject=subject.name) }}"
                               class="nav-link {% if request.view_args.get('subject') == subject.name %}active{% endif %}">{{ subject.name }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>

bqwebsite/templates/main/_products.html
<section class="portfolio">
    <div class="container">
        <div class="text-center mt-3 mb-3">
            <div class="row">
                {% if products %}
                    {% for product in products %}
                        {% if product.status %}
                            <div class="col-md-3 col-sm-6 mb-5">
                                <div class="product_hover_effect border">
                                    {% set photo = product.photos|first %}
                                    {% if photo %}
                                        <img src="{{ url_for('admin.get_image', filename=photo.filename_m) }}"
                                             alt="{{ product.name }}" class="img-fluid rounded"
                                             style="height:357px;object-fit: contain;">
                                    {% else %}
                                        <img src="{{ url_for('static', filename = 'assets/default.jpg') }}"
                                             alt="No photos." class="img-fluid rounded" style="object-fit: contain;">
                                    {% endif %}
                                    <div class="overlay">
                                        <h2 class="mt-5">{{ product.name }}</h2>
                                        <p class="">
                                            {{ product.product_indication }}
                                        </p>
                                        <a href="{{ url_for('main.show_product', product_id=product.id) }}"
                                           class="info">点击查看</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if products|selectattr('status')|list %}
                        <div class="pt-2">
                            {{ render_pagination(pagination, align='center', prev='上一页', next='下一页') }}
                        </div>
                    {% else %}
                        <div class="text-center">
                            <h3 class="my-5">暂无产品</h3>
                        </div>
                    {% endif %}
                {% else %}
                    <div class="text-center">
                        <h3 class="my-5">暂无产品</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>

bqwebsite/templates/main/_sidebar_product.html
<div class="col-lg-3 col-md-3 col-sm-12">
    <div class="list-group mb-3">
        <div class="list-group-item list-group-item-action bg-danger text-white fw-bold">
            热门产品
        </div>
        {% if hot_products %}
            {% for hot_product in hot_products %}
                <a href="{{ url_for('main.show_product', product_id=hot_product.id) }}"
                   class="list-group-item list-group-item-action">{{ hot_product.name }}</a>
            {% endfor %}
        {% else %}
            <div class="text-center">
                <h5>No Products</h5>
            </div>
        {% endif %}
    </div>
</div>

bqwebsite/templates/main/contact_cooperation.html
{% extends 'base.html' %}

{% block title %}
    {{ contact.title }}
{% endblock %}
{% block nav_contact %}active{% endblock %}
{% set active_page = contact.contact_category.name %}
{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="news_bg_img"><img src="{{ url_for('static', filename='assets/img/banner-contact.png') }}"
                                      class="img-fluid" alt=""></div>
    </header>
    <section class="page-section portfolio bg-light">
        <div class="container mt-5">
            <div class="row">
                {% include 'main/_sidebar_contact.html' %}
                <div class="col-lg-9 col-md-9 col-sm-12 bg-white rounded mt-3 mb-5">
                    {% for message in get_flashed_messages(with_categories = True) %}
                        <div class="alert alert-{{ message[0] }}" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            {{ message[1] }}
                        </div>
                    {% endfor %}
                    <h3 class="text-center text-dark mt-5">{{ contact.title }}</h3>
                    <p class="text-muted text-center"><small>发布时间：{{ moment(contact.timestamp).format('lll') }}</small></p>
                    <hr>
                    <p class="lh-lg text-start text-indent">{{ contact.content|safe }}</p>
                    <hr class="mt-5">
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bqwebsite/templates/main/news_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ news_detail.title }}
{% endblock %}
{% block nav_news %}active{% endblock %}
{% set active_page = news_detail.newscategory.name %}
{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="news_bg_img"><img src="{{ url_for('static', filename='assets/img/banner-news.png') }}"
                                      class="img-fluid" alt=""></div>
    </header>
    <section class="page-section portfolio bg-light">
        <div class="container">
            <div class="row">
                {% include 'main/_sidebar_news.html' %}
                <div class="col-lg-9 col-md-9 col-sm-12 bg-white rounded mt-3 mb-5">
                    {% for message in get_flashed_messages(with_categories = True) %}
                        <div class="alert alert-{{ message[0] }}" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            {{ message[1] }}
                        </div>
                    {% endfor %}
                    <nav aria-label="breadcrumb" class="mt-2 bg-white">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url_for('main.news') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">全部新闻</a></li>
                            <li class="breadcrumb-item"><a
                                    href="{{ url_for('main.show_news_category', news_category_id=news_detail.newscategory.id) }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{ news_detail.newscategory.name }}</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{ news_detail.title }}</li>
                        </ol>
                    </nav>
                    <h3 class="text-center text-dark mt-5">{{ news_detail.title }}</h3>
                    <p class="text-muted text-center"><small>发布时间：{{ moment(news_detail.timestamp).format('lll') }}</small></p>
                    <hr>
                    <div class="lh-lg text-start text-indent px-3">{{ news_detail.content | replace("<img", "<img class='img-fluid h-100'") | safe }}</div>
                    <hr class="mt-5">
                    <nav aria-label="Page navigation">
                        <ul class="pagination navbar">
                            <li class="page-item">
                                <a href="{{ url_for('main.news_previous', news_id=news_detail.id) }}"
                                   class="page-link">&larr;上一篇</a>
                            </li>
                            <li class="page-item">
                                <a href="{{ url_for('main.news_next', news_id=news_detail.id) }}" class="page-link">下一篇&rarr;</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bqwebsite/templates/main/product_brand.html
{% extends 'base.html' %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block title %}
    {{ brand.name }}-产品中心
{% endblock %}
{% block nav_products %}active{% endblock %}
{% block content %}
    {% include 'main/_product_header.html' %}
    {% include 'main/_products.html' %}
{% endblock %}

bqwebsite/templates/main/product_detail.html
{% extends 'base.html' %}

{% block title %}
    产品中心
{% endblock %}
{% block nav_products %}active{% endblock %}
{% block content %}
    <header class="masthead bg-primary text-white text-center">
        <div class="product_bg_img"><img src="{{ url_for('static', filename='assets/img/banner-products.png') }}"
                                         class="img-fluid"
                                         alt=""></div>
    </header>
    <section class="page-section portfolio bg-light py-5">
        <div class="container">
            <div class="row">
                {% include 'main/_sidebar_product.html' %}
                <div class="col-lg-9 col-md-9 col-sm-12 bg-white rounded">
                    <nav aria-label="breadcrumb" class="p-1 bg-white">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url_for('main.product') }}"
                                                           class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">全部产品</a>
                            </li>
                            <li class="breadcrumb-item"><a href="{{ url_for('main.product_category', category=product.category.name) }}"
                                                           class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{ product.category.name }}</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
                        </ol>
                    </nav>
                    <h3 class="text-center text-secondary mt-3 text-dark">{{ product.name }}</h3>
                    <p class="text-muted text-center">
                        <small>发布时间：{{ moment(product.timestamp).format('lll') }}</small></p>
                    <hr class="divider-custom">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            {% if product.photos.count() %}
                                {# 图片轮播 #}
                                <div id="productCarousel" class="carousel slide carousel-dark " data-bs-ride="carousel">
                                    <!-- 轮播指示器 -->
                                    <div class="carousel-indicators">
                                        {% for photo in product.photos %}
                                            <button type="button" data-bs-target="#productCarousel"
                                                    data-bs-slide-to="{{ loop.index0 }}"
                                                    class="{% if loop.first %}active{% endif %}"
                                                    aria-current="{% if loop.first %}true{% endif %}"
                                                    aria-label="Slide {{ loop.index }}"></button>
                                        {% endfor %}
                                    </div>
                                    <!-- 轮播项 -->
                                    <div class="carousel-inner">
                                        {% for photo in product.photos %}
                                            <div class="carousel-item {% if loop.first %}active{% endif %}"
                                                 data-bs-interval="3000">
                                                <img src="{{ url_for('admin.get_image', filename=photo.filename_m) }}"
                                                     alt="{{ product.name }}" class="d-block w-100 img-fluid rounded"
                                                     style="width: 400px; height: 500px; object-fit: contain;">
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% else %}
                                <div class="">
                                    <img src="{{ url_for('static', filename='assets/default.jpg') }}"
                                         alt="No photos." class="d-block w-100 img-fluid rounded"
                                         style="width: 400px; height: 500px; object-fit: contain;">
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <table class="table table-hover table-light text-center">
                                <tbody>
                                <tr>
                                    <th class="" style="white-space: nowrap;">产品名称:</th>
                                    <td>{{ product.name }}</td>
                                </tr>
                                <tr>
                                    <th>剂 型：</th>
                                    <td>{{ product.category.name }}</td>
                                </tr>
                                <tr>
                                    <th>规 格：</th>
                                    <td>{{ product.product_format }}</td>
                                </tr>
                                <tr>
                                    <th style="white-space: nowrap;">功能主治：</th>
                                    <td>{{ product.product_indication }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="text-start mt-5">
                        {{ product.product_content | replace("<img", "<img class='d-block mx-auto img-fluid h-100'") | safe }}
                    </div>
                    <hr class="mt-5">
                    <nav aria-label="Page navigation">
                        <ul class="pagination navbar">
                            <li class="page-item {% if not product_p_name %}disabled{% endif %}">
                                <a href="{{ url_for('main.product_previous', product_id=product.id) }}"
                                   class="btn btn-light page-link">
                                    {% if product_p_name %}
                                        上一个：{{ product_p_name }}
                                    {% else %}
                                        已经是第一个
                                    {% endif %}
                                </a>
                            </li>
                            <li class="page-item {% if not product_n_name %}disabled{% endif %}">
                                <a href="{{ url_for('main.product_next', product_id=product.id) }}"
                                   class="btn btn-light page-link">
                                    {% if product_n_name %}
                                        下一个：{{ product_n_name }}
                                    {% else %}
                                        已经是最后一个
                                    {% endif %}
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

bqwebsite/templates/main/product_subject.html
{% extends 'base.html' %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block title %}
    {{ subject.name }}-产品中心
{% endblock %}
{% block nav_products %}active{% endblock %}
{% block content %}
    {% include 'main/_product_header.html' %}
    {% include 'main/_products.html' %}
{% endblock %}