bqwebsite/blueprints/main.py
import os

from flask import render_template, request, redirect, url_for, Blueprint, current_app, flash, send_from_directory, \
    jsonify
from sqlalchemy.orm import joinedload, contains_eager

from ..models import Category, Product, News, Brand, Honor, Banner, Introduce, Photo, NewsCategory, \
    IntroduceCategory, Contact, ContactCategory, Subject, Research, ResearchCategory, IndexAbout

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
# 主页
def index():
    banner = Banner.query.all()
    index_about = IndexAbout.query.first()
    categories = Category.query.filter(Category.status == True).order_by(Category.id).all()
    filtered_categories = [category for category in categories if category.id >= 2][:8]
    news = News.query.filter(News.status == True).order_by(News.timestamp.desc()).all()
    return render_template('main/index.html', banner=banner, index_about=index_about, categories=filtered_categories, news=news)


@main_bp.route('/news-category/<int:news_category_id>')
# 新闻分类页面
def show_news_category(news_category_id):
    news_category = NewsCategory.query.get_or_404(news_category_id)
    if not news_category.status:
        flash('该新闻分类不存在', 'info')
        return redirect(url_for('main.news'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_NEWS_PER_PAGE']
    pagination = News.query.with_parent(news_category).filter(News.status == True).order_by(
        News.timestamp.desc()).paginate(page=page,
                                        per_page=per_page)
    news_list = pagination.items

    return render_template('main/news_category.html', news_category=news_category, news_list=news_list,
                           pagination=pagination)


@main_bp.route('/news/<int:news_id>')
# 新闻详细页面
def show_news(news_id):
    news_detail = News.query.get_or_404(news_id)
    if not news_detail.status:
        flash('该新闻不存在', 'info')
        return redirect(url_for('main.news'))
    return render_template('main/news_detail.html', news_detail=news_detail)


@main_bp.route('/news/n/<int:news_id>')
# 下一篇文章
def news_next(news_id):
    news_n_detail = News.query.get_or_404(news_id)
    if not news_n_detail.status:
        flash('该文章不存在', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    news_n = News.query.with_parent(news_n_detail.newscategory).filter(
        News.timestamp < news_n_detail.timestamp, News.status == True).order_by(News.timestamp.desc()).first()

    if news_n is None:
        flash('已经是最后一篇文章', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    return redirect(url_for('main.show_news', news_id=news_n.id))


@main_bp.route('/news/p/<int:news_id>')
# 上一篇文章
def news_previous(news_id):
    news_p_detail = News.query.get_or_404(news_id)
    if not news_p_detail.status:
        flash('该文章不存在', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    news_p = News.query.with_parent(news_p_detail.newscategory).filter(
        News.timestamp > news_p_detail.timestamp, News.status == True).order_by(News.timestamp.asc()).first()

    if news_p is None:
        flash('已经是最新一篇文章', 'info')
        return redirect(url_for('main.show_news', news_id=news_id))
    return redirect(url_for('main.show_news', news_id=news_p.id))


@main_bp.route('/news')
# 全部新闻页面
def news():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_NEWS_PER_PAGE']
    pagination = News.query.filter(News.status == True).order_by(News.timestamp.desc()).paginate(page=page,
                                                                                                 per_page=per_page)
    all_news = pagination.items
    return render_template('main/news.html', all_news=all_news, pagination=pagination)


@main_bp.route('/products')  # 所有产品
def product():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.filter(Product.status == True).order_by(Product.timestamp.desc()).paginate(page=page,
                                                                                                          per_page=per_page)
    products = pagination.items
    return render_template('main/products.html', products=products, pagination=pagination)


@main_bp.route('/category/<category>')  # 按剂型分类
def product_category(category):
    category = Category.query.filter_by(name=category).first_or_404()
    if not category.status:
        flash('该分类不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(category).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_category.html', category=category, pagination=pagination, products=products)


@main_bp.route('/brand/<brand>')  # 按商标分类
def product_brand(brand):
    brand = Brand.query.filter_by(name=brand).first_or_404()
    if not brand.status:
        flash('该商标不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(brand).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_brand.html', brand=brand, pagination=pagination, products=products)


@main_bp.route('/subject/<subject>')  # 按功能主治分类
def product_subject(subject):
    subject = Subject.query.filter_by(name=subject).first_or_404()
    if not subject.status:
        flash('该功能主治不存在', 'info')
        return redirect(url_for('main.product'))
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BQ_PRODUCT_PER_PAGE']
    pagination = Product.query.with_parent(subject).filter(Product.status == True).order_by(
        Product.timestamp.desc()).paginate(page=page,
                                           per_page=per_page)
    products = pagination.items
    return render_template('main/product_subject.html', subject=subject, pagination=pagination, products=products)


@main_bp.route('/products/n/<int:product_id>')
# 下一个品种
def product_next(product_id):
    product_n_detail = Product.query.get_or_404(product_id)
    if not product_n_detail.status:
        flash('该品种不存在', 'info')
        return redirect(url_for('main.product'))
    product_n = Product.query.with_parent(product_n_detail.category).filter(
        Product.timestamp > product_n_detail.timestamp).order_by(Product.timestamp.asc()).first()

    if product_n is None:
        flash('已经是一个', 'info')
        return redirect(url_for('main.show_product', product_id=product_id))
    return redirect(url_for('main.show_product', product_id=product_n.id))


@main_bp.route('/products/p/<int:product_id>')
# 上一个品种
def product_previous(product_id):
    product_p_detail = Product.query.get_or_404(product_id)
    if not product_p_detail.status:
        flash('该品种不存在', 'info')
        return redirect(url_for('main.product'))
    product_p = Product.query.with_parent(product_p_detail.category).filter(
        Product.timestamp < product_p_detail.timestamp).order_by(Product.timestamp.desc()).first()

    if product_p is None:
        flash('已经是最后一个', 'info')
        return redirect(url_for('main.show_product', product_id=product_id))
    return redirect(url_for('main.show_product', product_id=product_p.id))


@main_bp.route('/product_detail/<int:product_id>')  # 产品详细页面
def show_product(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.status:
        flash('该产品不存在', 'info')
        return redirect(url_for('main.product'))

    # 获取上一个品种
    product_p = Product.query.with_parent(product.category).filter(Product.timestamp < product.timestamp,
                                                                   Product.status == True).order_by(
        Product.timestamp.desc()).first()
    product_p_name = product_p.name if product_p else None
    # 获取下一个品种
    product_n = Product.query.with_parent(product.category).filter(Product.timestamp > product.timestamp,
                                                                   Product.status == True).order_by(
        Product.timestamp.asc()).first()
    product_n_name = product_n.name if product_n else None
    return render_template('main/product_detail.html', product=product, product_p_name=product_p_name,
                           product_n_name=product_n_name)


@main_bp.route('/introduce/<int:intro_id>')
# 公司介绍
def show_intro(intro_id):
    intro_categories = (
        IntroduceCategory.query
        .join(IntroduceCategory.introduces)  # 关联 Introduce 表
        .filter(Introduce.status == True)  # 筛选 status 为 True 的记录
        .options(contains_eager(IntroduceCategory.introduces))  # 预加载 introduces 数据
        .order_by(IntroduceCategory.id.asc())
        .all()
    )

    intro = Introduce.query.filter_by(id=intro_id, status=True).first_or_404()
    if not intro.status or not intro.introduce_category.status:
        flash('该介绍不存在', 'warning')
        return redirect(url_for('main.index'))
    return render_template('main/introduce_detail.html', intro=intro, intro_categories=intro_categories)


@main_bp.route('/honor')
# 荣誉介绍
def honor():
    return render_template('main/honor.html')


@main_bp.route('/contact/<int:contact_id>')
# 联系我们
def show_contact(contact_id):
    contact_categories = (
        ContactCategory.query
        .join(ContactCategory.contacts)
        .filter(Contact.status == True)
        .options(contains_eager(ContactCategory.contacts))
        .order_by(ContactCategory.id.asc())

bqwebsite/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="bangqi"/>
    <meta name="author" content="bangqi"/>
    {% block head %}
        <title>{% block title %}base{% endblock %}- 广西邦琪药业集团有限公司</title>
        {% block styles %}
            <!-- 集团logo -->
            <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename = 'assets/fav.ico') }}"/>
            <!-- Font Awesome icons (free version)-->
            <link rel="stylesheet" href="https://cdn.staticfile.net/font-awesome/6.4.0/css/all.min.css">
            <!-- Core theme CSS (includes Bootstrap)-->
            <link rel="stylesheet" href="{{ url_for('static',filename = 'css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.css">
            <!-- dropzone.js上传文件插件 -->
            <link href="{{ url_for('static',filename = 'admin/css/dropzone.min.css') }}" rel="stylesheet"/>

            <link href="{{ url_for('static',filename = 'admin/css/styles.css') }}" rel="stylesheet"/>
        {% endblock %}
    {% endblock %}
</head>

<body id="page-top">
{% block navbar %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}" target="_blank">邦琪后台管理系统</a>
            <ul class="navbar-nav"></ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-1 mx-lg-2">
                    <span class="nav-link px-0 rounded">超级管理员</span>
                </li>
                <li class="nav-item mx-1 mx-lg-2">
                    <a class="nav-link px-0 rounded" href="{{ url_for('admin.index') }}">Admin</a>
                </li>
                <li class="nav-item mx-1 mx-lg-2">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('admin.logout') }}">退出登录</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% for message in get_flashed_messages(with_categories = True) %}
        <div class="alert alert-{{ message[0] }} alert-floating" role="alert" id="flash-message-{{ loop.index }}">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            {{ message[1] }}
        </div>
    {% endfor %}
{% endblock %}

{% block content %}
{% endblock %}

<!-- Footer-->
{% block footer %}
    <!-- Copyright Section-->
    <div class="copyright py-4 text-center bg-dark text-white">
        <div class="container"><small>Copyright ©2023 广西邦琪药业集团有限公司 All Rights Reserved</small></div>
        <div class="container"><small>互联网药品信息服务资格证书：（桂）-非经营性-2023-0020号 <a
                href="https://beian.miit.gov.cn" target="_blank" class="px-0 px-lg-3 rounded"
                style="color: #fff; text-decoration: none">桂ICP备14001107号-1</a></small>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static',filename = 'js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static',filename = 'admin/js/dropzone.min.js') }}"></script>
    <script src="{{ url_for('static',filename = 'admin/js/scripts.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='admin/js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-CN') }}
    <script>
        // 验证上传图片大小，限制单个文件不能大于5MB
        function validateFiles(input) {
            const maxSize = 5 * 1024 * 1024; // 5MB
            const files = input.files;
            for (let i = 0; i < files.length; i++) {
                if (files[i].size > maxSize) {
                    alert(`文件 ${files[i].name} 过大，上传的文件大小不能超过5MB`);
                    input.value = ""; // Clear the input
                    return;
                }
            }
        }
    </script>
{% endblock %}
</body>
</html>

bqwebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="bangqi"/>
    <meta name="author" content="bangqi"/>
    {% block head %}
        <title>{% block title %}base{% endblock %}- 广西邦琪药业集团有限公司</title>
        {% block styles %}
            <!-- 集团logo -->
            <link rel="icon" type="image/x-icon" href="{{ url_for('static',filename = 'assets/fav.ico') }}"/>
            <!-- Core theme CSS (includes Bootstrap)-->
            <link rel="stylesheet" href="https://cdn.staticfile.net/font-awesome/6.5.1/css/all.min.css">
            <link rel="stylesheet" href="{{ url_for('static',filename = 'css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static',filename = 'css/swiper-bundle.min.css') }}">
            <link href="{{ url_for('static',filename = 'css/styles.css') }}" rel="stylesheet"/>
        {% endblock %}
    {% endblock %}
</head>

<body id="page-top">
{% block navbar %}
    <nav class="navbar navbar-expand-lg bg-white fixed-top bg-opacity-50" id="mainNav">
        <div class="container">
            <a class="navbar-brand p-0 me-0 me-lg-3" href="{{ url_for('main.index') }}" aria-label="邦琪集团">
                <img src="{{ url_for('static', filename = 'assets/img/logo.png') }}"
                     class="d-block my-1 img-fluid"
                     role="img" alt="bangqijituan" style="height:50px;width:auto;">
            </a>
            <button class="navbar-toggler font-weight-bold bg-dark text-white rounded" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                    aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse rounded py-4" id="navbarResponsive">
                <ul class="navbar-nav ms-auto nav-item-hover-effect">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-1 px-0 px-lg-4 rounded {% block nav_index %}{% endblock %}"
                           href="{{ url_for('main.index') }}">主 页
                        </a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1 dropdown">
                        <a class="nav-link py-1 px-0 px-lg-3 rounded {% block nav_products %}{% endblock %}"
                           href="{{ url_for('main.product') }}">产品中心
                        </a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-1 px-0 px-lg-3 rounded {% block nav_news %} {% endblock %}"
                           href="{{ url_for('main.news') }}">邦资讯
                        </a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-1 px-0 px-lg-3 rounded {% block nav_intro %}{% endblock %}"
                           href="{{ url_for('main.show_intro', intro_id=intro_categories[0].introduces[0].id) }}">公司介绍
                        </a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-1 px-0 px-lg-3 rounded {% block nav_research %}{% endblock %}"
                           href="{{ url_for('main.show_research', research_id=research_categories[0].researchs[0].id ) }}">研发生产
                        </a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-1 px-0 px-lg-3 rounded {% block nav_contact %}{% endblock %}"
                           href="{{ url_for('main.show_contact', contact_id=contact_categories[0].contacts[0].id) }}">联系我们
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% for message in get_flashed_messages(with_categories = True) %}
        <div class="alert alert-{{ message[0] }} alert-floating" role="alert" id="flash-message-{{ loop.index }}">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            {{ message[1] }}
        </div>
    {% endfor %}
{% endblock %}

{% block content %}
{% endblock %}

<!-- Footer-->
{% if not index_page %}
    <footer class="footer text-center bg-dark text-white pt-5 pb-2">
        <div class="container">
            <div class="row py-5">
                <div class="col-2">
                    <h5 class="mb-2">产品中心</h5>
                    <ul class="list-unstyled">
                        <li class="my-2"><a href="#" class="footer-font-style">膏 剂</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">糖 浆</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">颗 粒</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">片 剂</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">胶 囊</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">酊 剂</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">酊 剂</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">酊 剂</a></li>
                    </ul>
                </div>
                <div class="col-2">
                    <h5 class="mb-2">邦资讯</h5>
                    <ul class="list-unstyled">
                        <li class="my-2"><a href="#" class="footer-font-style">公司新闻</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">行业资讯</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">家庭护理</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">商标展示</a></li>
                    </ul>
                </div>
                <div class="col-2">
                    <h5 class="mb-2">公司介绍</h5>
                    <ul class="list-unstyled">
                        <li class="my-2"><a href="#" class="footer-font-style">公司介绍</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">质量机构</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">企业架构</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">社会责任</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">企业荣誉</a></li>
                    </ul>
                </div>
                <div class="col-2">
                    <h5 class="mb-2">研发中心</h5>
                    <ul class="list-unstyled">
                        <li class="my-2"><a href="#" class="footer-font-style">公司介绍</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">质量机构</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">企业架构</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">社会责任</a></li>
                        <li class="my-2"><a href="#" class="footer-font-style">企业荣誉</a></li>
                    </ul>
                </div>
                <div class="col-4">
                    <h5 class="mb-2">公司信息</h5>
                    <ul class="list-unstyled">
                        <li class="my-2">公司地址：广西钦州市钦北区皇马工业园</li>
                        <li class="my-2">公司电话：0777-3889528</li>
                        <li class="my-2">邮政编码：535038</li>
                        <li class="my-2"><img src="{{ url_for('static', filename='assets/img/wechat.svg') }}"
                                              alt="公司公众号" style="width:7rem;height:auto;"></li>
                    </ul>
                </div>
            </div>
            <!-- Copyright Section-->
            <div class="text-center mt-5">
                <span class="footer-info-style">Copyright ©2024 广西邦琪药业集团有限公司 All Rights Reserved</span>
                <span class="footer-info-style">
                        <a href="https://beian.miit.gov.cn" target="_blank" class="px-0 px-lg-3 rounded">桂ICP备14001107号-1</a>
                    </span>
                <span class="footer-info-style">
                        <a href="https://beian.miit.gov.cn" target="_blank" class="px-0 px-lg-3 rounded">桂公网安备 45030202000001号</a>
                    </span>
            </div>
        </div>
    </footer>

{% endif %}



{% block scripts %}
    <script src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/swiper-bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename = 'js/scripts.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-CN') }}
{% endblock %}
</body>
</html>

bqwebsite/templates/macros.html
{# nav_link宏 #}
{% macro nav_link(endpoint, text) -%}
    <a class="list-group-item list-group-item-action {% if request.endpoint and request.endpoint == endpoint %}active{% endif %} ">
        <a href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
    </a>
{% endmacro %}

{# 表单渲染宏 #}
{% macro render_field(field) -%}
    <div class="form-group">
        {{ field.label }}
        {{ field(class='form-control', **kwargs) }}
        {% if field.errors %}
            <ul class="alert-error">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endmacro %}